from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse, reverse_lazy
from django.http import JsonResponse, Http404, HttpResponse
from django.views.generic import View, TemplateView
from django.forms.models import model_to_dict
from django.template.loader import render_to_string
from django.contrib import messages
from django.views.decorators.csrf import csrf_exempt
from django.utils.decorators import method_decorator
from django.conf import settings
from  urllib.parse import urlencode
from decimal import Decimal
import hmac
import hashlib
import json


from cart.cart import Cart
from .forms import OrderForm
from shop.models import Order, OrderItem
from .paystack import checkout


class CartView(View):
    def get(self, request):
        cart = Cart(request)
        context = {"cart":cart}

        return render(request, "cart/cart_page.html", context)

    def post(self, request):
        cart = Cart(request)
        cart_id = request.POST.get("id")
        cart_quantity = int(request.POST.get("quantity"))

        cart.add(cart_id, cart_quantity, True)
        
        html = render_to_string(
            "cart/includes/cart_list.html", 
            {"cart":cart, "reload":True}, 
            request
        )
            
        return JsonResponse({"html":html, "status":True, "cart":len(cart)})
    




class AddToCartView(View):
    def get(self, request, id):
        quantity = request.GET.get("quantity")
        cart = Cart(request)
        if quantity:
            cart.add(id, quantity=int(quantity))
        else:
            cart.add(id,)
        

        return redirect(reverse("cart"))



class UpdateCartView(View):
    def get(self, request, id):
        cart = Cart(request)
        quantity = request.GET.get("quantity")
        cart.add(product_id=id, quantity=quantity, update_quantity=True)

        return redirect(reverse("cart"))



class RemoveFromCartView(View):
    def get(self, request, id):
        cart = Cart(request)
        cart.remove(id)

        return redirect(reverse("cart"))
    



class CheckoutView(View):
    def get(self, request):
        cart = Cart(request)
        form = OrderForm()

        context = {
            "cart":cart,
            "form":form
                   }

        return render(request, "cart/checkout_page.html", context)
    

    def post(self, request):
        cart = Cart(request)
        form = OrderForm(request.POST)

        if form.is_valid():
            form.total_amount = cart.get_total_cost() 
            order = form.save()

            components_to_create = [] 

            for items in cart:
                product = items["product"]
                quantities = items["quantity"]

                components_to_create.append(
                    OrderItem(order=order, product=product, quantities=quantities)
                )

            OrderItem.objects.bulk_create(components_to_create)

            query_param = {
                "order_id": order.id
            }
            encoded_param = urlencode(query_param)

            payment_success_url = f"{reverse_lazy('checkout_success')}?{encoded_param}"
            
            # http://domain.com/payment-success/2/ 
            callback_url = f"{request.scheme}://{request.get_host()}{payment_success_url}"

            checkout_data = {
                "email": order.email,
                "amount": float(order.total()) * 100,  # in kobo (₦2500)
                "currency": "NGN",
                "channels": ["card", "bank_transfer", "bank", "ussd", "qr", "mobile_money"],
                "reference": str(order.id), # generated by developer
                "callback_url": callback_url,
                "metadata": {
                    "order_id": str(order.id),
                    # "user_id": request.user.id,
                    # "purchase_id": purchase_id,
                },
                "label": f"Checkout For Order No. {order.id}"
            }
            
            status, check_out_session_url_or_error_message = checkout(checkout_data)

            if status:
                return redirect(check_out_session_url_or_error_message)
            else:
                messages.error(request, check_out_session_url_or_error_message)
                order.delete()


        context = {
            "cart":cart,
            "form":form
        }

        return render(request, "cart/checkout_page.html", context)
    

@method_decorator(csrf_exempt, name="dispatch")
class PaystackWebhook(View):
    def post(self, request):
        secret = settings.PAYSTACK_SECRET_KEY
        request_body = request.body

        hash = hmac.new(secret.encode("utf-8"), request_body, hashlib.sha512).hexdigest()

        if hash == request.META.get("HTTP_X_PAYSTACK_SIGNATURE"):
            webhook_post_data = json.loads(request_body)

            if webhook_post_data["event"] == "charge.success":
                metadata = webhook_post_data["data"]["metadata"]

                order_id = metadata["order_id"]

                order = get_object_or_404(Order, id=order_id)
                order.paid = True
                order.save()

        return HttpResponse(status=200)



    
class CheckOutSuccessView(View):
    def get(self, request):
        cart = Cart(request)
        cart.clear()
        order_id = request.GET.get("order_id")
        if order_id:
            order = Order.objects.filter(id=order_id).first()
            if order:
                context = {
                    "order":order
                }
                return render(request, "cart/order_success_page.html", context)
        
        return Http404()
    

