"""
Django settings for osaschops project.

Generated by 'django-admin startproject' using Django 5.2.8.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import environ
import os
import dj_database_url

env = environ.Env(
    DEBUG=(bool, True),
    SECRET_KEY=(str, "jhviiivsosovn")
)

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

environ.Env.read_env(os.path.join(BASE_DIR, ".env"))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-z2i19b8i94q!yyq%t=_%j6d-cztrf1y%-i)j-50bjod@2c(mpq'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env("DEBUG")

if DEBUG == False:
    DOMAIN_NAME = env("ALLOWED_HOSTS", default="")
    ALLOWED_HOSTS = [DOMAIN_NAME]

    CSRF_TRUSTED_ORIGINS = [
        f"https://{DOMAIN_NAME}",
        f"http://{DOMAIN_NAME}"
    ]

else:
    ALLOWED_HOSTS = ["*", "127.0.0.1"]

    CSRF_TRUSTED_ORIGINS = [
        "https://*.ngrok.io",
        "https://*.ngrok-free.app"
    ]



# Application definition

INSTALLED_APPS = [
    'daphne',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.humanize',

    "tailwind",
    "theme",

    "shop",
    "cart",
    "vendor",

    "channels",
    "phonenumber_field",

    "storages",

    # for file removal after changes
    "django_cleanup.apps.CleanupConfig",
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'osaschops.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            BASE_DIR/"templates",
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                "cart.context_processors.cart_context_processor"
            ],
        },
    },
]

WSGI_APPLICATION = 'osaschops.wsgi.application'
ASGI_APPLICATION = 'osaschops.asgi.application'

# Redis Channel Layer
CHANNEL_LAYERS = {
    # 'default': {
    #     'BACKEND': 'channels_redis.core.RedisChannelLayer',
    #     'CONFIG': {
    #         "hosts": [('127.0.0.1', 6379)],
    #     },
    # },
    "default": {
        "BACKEND": "channels.layers.InMemoryChannelLayer"
    }
}

# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

if DEBUG == False:
    DATABASES = {
        "default": dj_database_url.parse(
            url=env("DATABASE_URL"),
            conn_max_age=600, # Optional: controls connection pooling
            conn_health_checks=True # Optional: checks connection health
        )
    }

    STORAGES = {
        "default": {
            "BACKEND": "storages.backends.s3boto3.S3Boto3Storage",
        },
        "staticfiles": {
            "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
        },
    }


    AWS_ACCESS_KEY_ID = env("BACKBLAZE_S2_KEY_ID")
    AWS_SECRET_ACCESS_KEY = env("BACKBLAZE_S2_SECRET_KEY")
    AWS_STORAGE_BUCKET_NAME = env("BACKBLAZE_S2_NAME")
    AWS_S3_REGION_NAME = env("AWS_S3_REGION_NAME")
    AWS_S3_ENDPOINT_URL = f'https://s3.{AWS_S3_REGION_NAME}.backblazeb2.com' 
    AWS_S3_FILE_OVERWRITE = False

else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }



# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Africa/Lagos'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [
    BASE_DIR/"static"
]
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


TAILWIND_APP_NAME = 'theme'
NPM_BIN_PATH = "C:/Program Files/nodejs/npm.cmd"

CART_SESSION_ID = "cart"

if DEBUG == False:
    MEDIA_URL = f"{AWS_S3_ENDPOINT_URL}/{AWS_STORAGE_BUCKET_NAME}/media/"
else:
    MEDIA_URL = 'media/'
MEDIA_ROOT = BASE_DIR/"media"

PAYSTACK_SECRET_KEY = env("PAYSTACK_SECRET_KEY")

CACHES = {
    "default":{
        "BACKEND":"django.core.cache.backends.locmem.LocMemCache",
        "LOCATION":"unique-local-cache-1",
        "TIMEOUT": 300,
        "OPTIONS": {
            "MAX_ENTRIES":1000
        }
    }
}

PHONENUMBER_DEFAULT_REGION = "NG"

LOGIN_URL = "/vendor/login/"