# Generated by Django 6.0 on 2026-01-21 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_remove_orderitem_notes_remove_orderitem_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='icon_emoji',
            field=models.CharField(default='🥟', help_text='Enter a single emoji (e.g., 🍗, 🥤, 🍱)', max_length=10),
        ),
    ]
