# Generated by Django 6.0 on 2026-01-31 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_alter_eventinquiry_package_choice_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventinquiry',
            name='package_choice',
            field=models.CharField(max_length=255),
        ),
    ]
