# Generated by Django 6.0 on 2026-02-03 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_alter_eventinquiry_package_choice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventinquiry',
            name='package_choice',
        ),
        migrations.AddField(
            model_name='eventinquiry',
            name='package_choice',
            field=models.ManyToManyField(help_text='Please select one or more of the packages', to='shop.product'),
        ),
    ]
